name: Fix Code Style

on:
  pull_request:
    branches:
      - main # Sesuaikan dengan branch utama Anda
    types: [opened, synchronize, reopened] # Jalankan saat PR dibuka, diperbarui, atau dibuka kembali

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4] # Sesuaikan dengan versi PHP yang digunakan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply Pint fixes" # Pesan commit untuk perubahan yang dibuat oleh Pint
          branch: ${{ github.head_ref }} # Commit ke branch yang sama dengan pull request
